import {
  Code2,
  Globe,
  Smartphone,
  ShoppingBag,
  Megaphone,
  Cloud,
  Sparkles,
  GitBranch,
  Plug,
  ShieldCheck,
  LifeBuoy,
  Wrench,
  Server,
  Database,
  Layers,
  Boxes,
  Compass,
  Lightbulb,
  PenTool,
  Rocket,
  TrendingUp,
  Bug,
  Gauge,
  Lock,
  Package,
  Users,
  Infinity as InfinityIcon,
  Repeat,
  Target,
  Eye,
  Heart,
  CheckCircle2,
  Phone,
  Mail,
  MapPin,
  MessageCircle,
  Workflow,
  Network,
  Cpu,
  Zap,
  LineChart,
  Search,
  FileText,
  Settings,
  Building2,
  Headset,
  Activity,
  Accessibility,
  Palette,
  Webhook,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

export const iconMap = {
  code: Code2,
  globe: Globe,
  smartphone: Smartphone,
  store: ShoppingBag,
  megaphone: Megaphone,
  cloud: Cloud,
  sparkles: Sparkles,
  "git-branch": GitBranch,
  plug: Plug,
  webhook: Webhook,
  shield: ShieldCheck,
  lifebuoy: LifeBuoy,
  wrench: Wrench,
  server: Server,
  database: Database,
  layers: Layers,
  boxes: Boxes,
  compass: Compass,
  lightbulb: Lightbulb,
  "pen-tool": PenTool,
  rocket: Rocket,
  trending: TrendingUp,
  bug: Bug,
  gauge: Gauge,
  lock: Lock,
  package: Package,
  users: Users,
  infinity: InfinityIcon,
  repeat: Repeat,
  target: Target,
  eye: Eye,
  heart: Heart,
  check: CheckCircle2,
  phone: Phone,
  mail: Mail,
  "map-pin": MapPin,
  message: MessageCircle,
  workflow: Workflow,
  network: Network,
  cpu: Cpu,
  zap: Zap,
  chart: LineChart,
  search: Search,
  file: FileText,
  settings: Settings,
  building: Building2,
  headset: Headset,
  activity: Activity,
  accessibility: Accessibility,
  palette: Palette,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export function Icon({
  name,
  className,
}: {
  name: IconName;
  className?: string;
}) {
  const Cmp = iconMap[name] ?? Code2;
  return <Cmp className={cn("h-5 w-5", className)} aria-hidden="true" />;
}
